accounts/urls.py
from django.conf.urls import url
from .import views

app_name = 'accounts'

urlpatterns = [
	url('signup/', views.signup_view, name = "signup"),
	url('login', views.login_view, name = "login"),
	url('logout', views.logout_view, name = "logout"),
    url('forgot', views.forgot, name = "forgot"),
    url('change_password', views.change_password, name = "change_password"),
]

articles/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name = 'list'),
    path('create', views.article_create, name = 'create'),
    path('<slug>/', views.article_detail, name = 'detail'),
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('about/', views.about),
    path('', article_views.article_list, name = 'home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
	title = models.CharField(max_length = 100)
	slug = models.SlugField()
	body = models.TextField()
	date = models.DateTimeField(auto_now_add = True)
	thumb = models.ImageField(default = 'default.png', blank = True)
	author = models.ForeignKey(User, default = None, on_delete = models.SET_DEFAULT)

	def __str__(self):
		return self.title

	def snippet(self):
		return self.body[:50] + "..."

articles/forms.py
from django import forms
from .import models

class CreateArticle(forms.ModelForm):
	class Meta:
		model = models.Article
		fields = ('title', 'body', 'slug', 'thumb')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout,authenticate
from django.contrib.auth.models import User
# Create your views here.
def signup_view(request):
	if request.method == "POST":
		uname =  request.POST["uname"]
		passwd = request.POST["passwd"]
		user = User.objects.create_user(username=uname,password=passwd)
		user.save()
		return render(request, 'accounts/login.html')
	else:
		return render(request, 'accounts/signup.html')

def login_view(request):
	if request.method == "POST":
			uname =  request.POST["uname"]
			passwd = request.POST["passwd"]
			user = authenticate(request,username=uname,password=passwd)
			if user is not None:
				login(request, user)
				return redirect('articles:list')
			else:
				return render(request, 'accounts/login.html')
	else:
		return render(request, 'accounts/login.html')

def logout_view(request):
	if request.method == "POST":
		logout(request)
		return redirect('articles:list')
def forgot(request):
	if request.method == "POST":
		global uname
		uname = request.POST["uname"]
		user = User.objects.filter(username=uname)
		print(user)
		if user:
			return redirect('accounts:change_password')
		else:
			return redirect('accounts:login')
	else:
		return render(request,'accounts/forgot.html')
def change_password(request):
	if request.method == "POST":	
		pas=request.POST["passwd"]
		u = User.objects.get(username=uname)
		u.set_password(pas)
		u.save()
		return redirect('accounts:login')
	else:
		return render(request,'accounts/change_password.html')

articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .import forms

# Create your views here.
def article_list(request):
	articles = Article.objects.all().order_by('date')
	return render(request, 'articles/article_list.html', {'articles': articles})

def article_detail(request, slug):
	#return HttpResponse(slug)
	article = Article.objects.get(slug=slug)
	return render(request, 'articles/article_detail.html', {'article': article})

@login_required(login_url = '/accounts/login/')
def article_create(request):
	if request.method == "POST":
		form = forms.CreateArticle(request.POST, request.FILES)
		if form.is_valid():
			#save article to db
			form.save(commit = False)
			instance = form.save(commit = False)
			instance.author = request.user
			instance.save()
			return redirect('articles:list')
	else:
		form = forms.CreateArticle()
	return render(request, 'articles/article_create.html', {'form': form})

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
	# return HttpResponse('homepage')
	return render(request, 'home.html')

def about(request):
	# return HttpResponse('about')
	return render(request, 'about.html')

accounts/templates/accounts/change_password.html
<html>
<head>
<title>change password</title>
<style>
	*{
		margin:0;
		padding:0;
	}
	body{
		display:flex;
		justify-content:center;
		align-items:center;
		background-image:linear-gradient(to bottom, rgb(20, 1, 56), rgb(21, 6, 94));
		min-height:100vh;
	}
	.box{
		position:relative;
		width:380px;
		height:280px;
		margin: 100px;
		background: rgba(96, 111, 208, 0.33);
		border-radius: 16px;
		box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
		backdrop-filter: blur(0px);
		-webkit-backdrop-filter: blur(0px);
		border: 1px solid rgba(9, 9, 9, 1);
	}
	.box form{
		position:absolute;
		left:30px;
		inset:4px;
		padding:50px 40px;
		border-radius:20px;
		display:flex;
		flex-direction:column;
	}
	.box form h1{
		color:aliceblue;
		text-align:center;
		letter-spacing:0.1em;
	}
	.box form .input_box{
		position:relative;
		width:250px;
		margin-top:35px;
        margin-left: 20px;
	}
	.box form .input_box input{
		position:relative;
		width:100%;
		padding:20px 10px 10px;
		background:transparent;
		box-shadow:none;
		outline:none;
		color:aliceblue;
		border:none;
		font-size:1em;
        text-align: center;
		transition:0.5s;
		letter-spacing:0.05em;
		z-index:10;
	}
	.box form .input_box span{
		position:absolute;
		left:0;
		padding:20px 10px 10px;
		pointer-events:none;
		color:aliceblue;
		font-size:1em;
		transition:0.5s;
		letter-spacing:0.05em;
	}
	
	.box form .input_box input:focus ~ span{
		color:aliceblue;
		font-size:0.75em;
		transform:translatey(-34px);
	}
	.box form .input_box i{
		position:absolute;
		left:0;
		bottom:0;
		width:100%;
		height:2px;
		background-color:rgb(35, 153, 157);
		overflow:hidden;
		transition:0.5s;
	}
	
	#signup{
		border-radius: 30px;
        border: none;
		cursor: pointer;
        margin-top: 45px;
        padding: 10px;
        background:rgb(157, 180, 200);
        box-shadow: 1px 1px 5px 2px;
	}
	#signup:hover{
		transition: 1s;
		background-color: aliceblue;
    	box-shadow: none;
	}
</style>
</head>
<body>
	<div class="box">
		<form action="{% url 'accounts:change_password' %}" method="post">
		{% csrf_token %}
		<h1>Enter New Password</h1>
		<div class='input_box'>
			<input type="password" name="passwd">
			<i></i>
		</div>
			<br><input id="signup" type="submit" value="Enter"></br>
		
		
	</div>
</body>
</html>

accounts/templates/accounts/forgot.html
<html>
<head>
<title>Forgot</title>
<style>
	*{
		margin:0;
		padding:0;
	}
	body{
		display:flex;
		justify-content:center;
		align-items:center;
		background-image:linear-gradient(to bottom, rgb(20, 1, 56), rgb(21, 6, 94));
		min-height:100vh;
	}
	.box{
		position:relative;
		width:380px;
		height:240px;
		margin: 100px;
		background: rgba(96, 111, 208, 0.33);
		border-radius: 16px;
		box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
		backdrop-filter: blur(0px);
		-webkit-backdrop-filter: blur(0px);
		border: 1px solid rgba(9, 9, 9, 1);
	}
	.box form{
		position:absolute;
		left:30px;
		inset:4px;
		padding:50px 40px;
		border-radius:20px;
		display:flex;
		flex-direction:column;
	}
	.box form h1{
		color:aliceblue;
		text-align:center;
		letter-spacing:0.1em;
	}
	.box form .input_box{
		position:relative;
		width:250px;
		margin-top:20px;
        margin-left: 20px;
	}
	.box form .input_box input{
		position:relative;
		width:100%;
		padding:20px 10px 10px;
		background:transparent;
		box-shadow:none;
		outline:none;
		color:aliceblue;
		border:none;
		font-size:1em;
        text-align: center;
		transition:0.5s;
		letter-spacing:0.05em;
		z-index:10;
	}
	.box form .input_box span{
		position:absolute;
		left:0;
		padding:20px 10px 10px;
		pointer-events:none;
		color:aliceblue;
		font-size:1em;
		transition:0.5s;
		letter-spacing:0.05em;
	}
	
	.box form .input_box input:focus ~ span{
		color:aliceblue;
		font-size:0.75em;
		transform:translatey(-34px);
	}
	.box form .input_box i{
		position:absolute;
		left:0;
		bottom:0;
		width:100%;
		height:2px;
		background-color:rgb(35, 153, 157);
		overflow:hidden;
		transition:0.5s;
	}
	
	#signup{
		border-radius: 30px;
        border: none;
		cursor: pointer;
        margin-top: 20px;
        padding: 10px;
        background:rgb(157, 180, 200);
        box-shadow: 1px 1px 5px 2px;
	}
	#signup:hover{
		transition: 1s;
		background-color: aliceblue;
    	box-shadow: none;
	}
</style>
</head>
<body>
	<div class="box">
		<form action="{% url 'accounts:forgot' %}" method="post">
		{% csrf_token %}
		<h1>Enter User Name</h1>
		<div class='input_box'>
			<input type="text" name="uname">
			<i></i>
		</div>
			<br><input id="signup" type="submit" value="Enter"></br>
		
		
	</div>
</body>
</html>

accounts/templates/accounts/login.html
<html>
<head>
<title>Login</title>
<style>
	*{
		margin:0;
		padding:0;
	}
	body{
		display:flex;
		justify-content:center;
		align-items:center;
		background-image:linear-gradient(to bottom, rgb(20, 1, 56), rgb(21, 6, 94));
		min-height:100vh;
	}
	.box{
		position:relative;
		width:380px;
		height:390px;
		margin: 100px;
		
		background: rgba(96, 111, 208, 0.33);
		border-radius: 16px;
		box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
		backdrop-filter: blur(0px);
		-webkit-backdrop-filter: blur(0px);
		border: 1px solid rgba(9, 9, 9, 1);
	}
	.box form{
		position:absolute;
		left:30px;
		inset:4px;
		padding:50px 40px;
		border-radius:20px;
		display:flex;
		flex-direction:column;
	}
	.box form h1{
		color:aliceblue;
		text-align:center;
		letter-spacing:0.1em;
	}
	.box form .input_box{
		position:relative;
		width:300px;
		margin-top:35px;
	}
	.box form .input_box input{
		position:relative;
		width:100%;
		padding:20px 10px 10px;
		background:transparent;
		box-shadow:none;
		outline:none;
		color:aliceblue;
		border:none;
		font-size:1em;
		transition:0.5s;
		letter-spacing:0.05em;
		z-index:10;
	}
	.box form .input_box span{
		position:absolute;
		left:0;
		padding:20px 10px 10px;
		pointer-events:none;
		color:aliceblue;
		font-size:1em;
		transition:0.5s;
		letter-spacing:0.05em;
	}
	
	.box form .input_box input:focus ~ span{
		color:aliceblue;
		font-size:0.75em;
		transform:translatey(-34px);
	}
	.box form .input_box i{
		position:absolute;
		left:0;
		bottom:0;
		width:100%;
		height:2px;
		background-color:rgb(35, 153, 157);
		overflow:hidden;
		transition:0.5s;
	}
	

        .box form .forgot{
                display:flex;
                justify-content:space-between;
        }
	.box form .forgot a{
		margin:10px 0;
		font-size:0.89em;
		color:aliceblue;
		text-decoration:none;
	}

        .box form input{
		border:none;
  		border-radius:2px;
		padding:7px;
		background:rgb(157, 180, 200);
	}
	#login{
		border-radius: 30px;
		cursor: pointer;
		margin-top: 20px;
	}
	#login:hover{
		color: rgb(38, 39, 39);
		transition: 1s;
		background-color: aliceblue;
	}
</style>
</head>
<body>
	<div class="box">
		<form action="{% url 'accounts:login' %}" method="post">
		{% csrf_token %}
		<h1>Login</h1>
		<div class='input_box'>
			<input type="text" name="uname" placeholder='User Name'>
			<i></i>
		</div>
		<div class='input_box'>
			<input type="password" name="passwd" placeholder="Password">
			<i></i>
		</div>
			<br><input id="login" type="submit" value="Login"></br>
		<div class='forgot'>
			<a href="{% url 'accounts:forgot' %}">Forgot Password?</a>
			<a href="{% url 'accounts:signup' %}">Sign Up?</a>
		</div>
		
	</div>
</body>
</html>

accounts/templates/accounts/signup.html
	<html>
		<head>
		<title>signup</title>
		<style>
			*{
				margin:0;
				padding:0;
			}
			body{
				display:flex;
				justify-content:center;
				align-items:center;
				background-image:linear-gradient(to bottom, rgb(20, 1, 56), rgb(21, 6, 94));
				min-height:100vh;
			}
			.box{
				position:relative;
				width:380px;
				height:380px;
				margin: 100px;
				background: rgba(96, 111, 208, 0.33);
				border-radius: 16px;
				box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
				backdrop-filter: blur(0px);
				-webkit-backdrop-filter: blur(0px);
				border: 1px solid rgba(9, 9, 9, 1);
			}
			.box form{
				position:absolute;
				left:30px;
				inset:4px;
				padding:50px 40px;
				border-radius:20px;
				display:flex;
				flex-direction:column;
			}
			.box form h1{
				color:aliceblue;
				text-align:center;
				margin-top: -20px;
				letter-spacing:0.1em;
			}
			.box form .input_box{
				position:relative;
				width:300px;
				margin-top:35px;
			}
			.box form .input_box input{
				position:relative;
				width:100%;
				padding:20px 10px 10px;
				background:transparent;
				box-shadow:none;
				outline:none;
				color:aliceblue;
				border:none;
				font-size:1em;
				transition:0.5s;
				letter-spacing:0.05em;
				z-index:10;
			}
			.box form .input_box span{
				position:absolute;
				left:0;
				padding:20px 10px 10px;
				pointer-events:none;
				color:aliceblue;
				font-size:1em;
				transition:0.5s;
				letter-spacing:0.05em;
			}
			
			.box form .input_box input:focus ~ span{
				color:aliceblue;
				font-size:0.75em;
				transform:translatey(-34px);
			}
			.box form .input_box i{
				position:absolute;
				left:0;
				bottom:0;
				width:100%;
				height:2px;
				background-color:rgb(35, 153, 157);
				overflow:hidden;
				transition:0.5s;
			}
			
			#signup{
				border-radius: 30px;
				border: none;
				cursor: pointer;
				margin-top: 30px;
				padding: 10px;
				background:rgb(157, 180, 200);
			}
			#signup:hover{
				transition: 1s;
				background-color: aliceblue;
				box-shadow: none;
		
			}
		</style>
		</head>
		<body>
			<div class="box">
				<form action="{% url 'accounts:signup' %}" method="post">
				{% csrf_token %}
				<h1>Sign up</h1>
				<div class='input_box'>
					<input type="text" name="uname" placeholder='User Name'>
					<i></i>
				</div>
				<div class='input_box'>
					<input type="password" name="passwd" placeholder="Password">
					<i></i>
				</div>
					<br><input id="signup" type="submit" value="Sign up"></br>
				
				
			</div>
		</body>
		</html>
		
		

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

	{% block content %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Articles Create</title>
	<link rel="stylesheet" type="text/css" href="/static/style.css">
<style>
	.main1{
		color: white;
		background-image: linear-gradient(to right,#2963A2, #4CAABC, #72C2C9);
		border-radius: 10px;
	}
	h2{
		font-size:40px;
		padding: 20px;
	}
	h3{
		font-size:25px;
		content:center;
	}
	.create-article {
		display:block;
	}
	.create-article .site-form {
		font-size:20px;
    		
	}
	.create-article .site-form input{
  		max-width: 200px;
 		width: 40px;
  		height: 40px;
  		outline: none;
  		margin: 5px;
  		margin-left:10px;
  		transition: .5s;
  		border: none;
  		border-radius: 40px;
  		padding: 10px;
  		text-align:center;
  		overflow: hidden;
 		white-space: nowrap;
		color: black;
  		text-overflow: ellipsis;
  		transform: rotate(0);
  		background-color: rgb(253, 253, 253);
  		font-size:20px;
	}
	.create-article .site-form input:focus {
  		width: 150px;
  		transform: rotate(0);
	}
    textarea{
        border-radius: 50px;
        margin:10px;
        display: flex;
  		flex-wrap: wrap;
  		padding:30px;
  		font-size:20px;
  		resize: vertical;
		color: black;
        box-shadow: rgba(0, 0, 0, 0.17) 0px -23px 25px 0px inset, rgba(0, 0, 0, 0.15) 0px -36px 30px 0px inset, rgba(0, 0, 0, 0.1) 0px -79px 40px 0px inset, rgba(0, 0, 0, 0.06) 0px 2px 1px,  rgba(0, 0, 0, 0.06) 0px 4px 2px,  rgba(0, 0, 0, 0.06) 0px 8px 4px,  rgba(0, 0, 0, 0.06) 0px 16px 8px,  rgba(0, 0, 0, 0.06) 0px 32px 16px;
	}
	.create-article input[name=""]{
		width:90%;
		height:50px;
		margin-top:10px;
		background:rgba(198, 198, 208, 0.622);
		color:rgb(5, 5, 5);
		cursor: pointer;
		margin-left:5.2cm;
		transform: rotate(0);
	}
	.create-article input[name="thumb"]{
 		width: 150px;
  		height: 40px;
  		border-radius: 20px;
		color: black;
  		background-color: rgb(253, 253, 253);
  		color:black;
  		font-size:20px;
	}
	.create-article input[name=""]:hover{
		background-color: #2963A2;
	}
	.main1{
		background-color: rgba(0, 0, 255, 0.618);
		border-radius: 10px;
		margin: 10px;
		border: none;
	}
</style>
</head>
<body>
	<div class="main1">
	<div class="main2">
		<div class="create-article">
			<h2>Create an Awesome Article</h2>
			<form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}

				{{ form }}
				<input type="submit" name="" value="Create">
			</form>
		</div>
		</div>
		</div>
</body>
</html>
	{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="article-detail">
	<div class="article">
		<h2>{{ article.title }}</h2>
		<img src="{{ article.thumb.url }}">
		<p>{{ article.body }}</p>
		<p>{{ article.date }}</p>
	</div>
</div>

{% endblock %}

articles/templates/articles/article_list.html
{%extends 'base_layout.html'%}
	{% block content %}
		
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Articles</title>
	<link rel="stylesheet" type="text/css" href="/static/style.css">
	<style>

		body{
			background-color: white;
		}
		.main{
			background-image: linear-gradient(to right,#2963A2, #4CAABC, #72C2C9);
			border-radius: 10px;
		}
		h1{
			color:rgb(59, 2, 74);
			font-size:50px;
			margin-left:30px;
			margin-top:10px;
		}
		.articles{
			font-size:20px;
			margin-left:60px;
			display:grid;
			grid-template-columns: 1fr;
			grid-gap: 30px;
			margin-top:30px;
			margin-right:60px;	
		}
		p{
			margin-left:20px;
		}
		.article{
			position:relative;
			backdrop-filter: blur(7px) saturate(200%);
   			-webkit-backdrop-filter: blur(7px) saturate(200%);
   			background-color: rgba(76, 104, 157, 0.484);
   			border-radius: 12px;
   			border: 1px solid rgba(255, 255, 255, 0.125);
			margin: 10px;
			padding: 20px;
			
		}
		.auth{
			margin-right:20px;
			background-color:red;
			color:white;
			padding: 10px;
			background: rgba(74, 57, 153, 0.358);
			position: absolute;
			right: 0;
			bottom: 0;
			border-radius:20px;
		}
		
	</style>
	<div class="main">
	<h1>Articles</h1>
	<div class="articles">
		{% for article in articles %}
			<div class="article">
				<h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
				<p>{{article.snippet}}</p>
				<p>{{article.date}}</p>
				<p class="auth">added by {{article.author.username}}</p>
			</div>
		{% endfor %}
	</div>
	</div>
	{% endblock %}

templates/about.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>About | Blog</title>
</head>
<body>
	<h1>ABOUT</h1>
	<p>Welcome to the About</p>
</body>
</html>

templates/base_layout.html
{% load static from static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Articles</title>
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<style>
		nav{
	display: flex;
	justify-content: center;
	align-items: center;
}
nav li{
	display: inline-block;
	position: relative;
	right: 30px;
}
nav ul li .button{
	position: relative;
	background: none;
	color: #fff;
	cursor: pointer;
	top:40px;
	right: 40px;
	position: relative;
	border: 0;
	font-size: 1.2em;
}
</style>
</head>
<body>
	<div class="" style="background-color: white; color: black;border-radius: 10px">
		<header style="background-image: linear-gradient(to right,#174e89, #23869a, #208892)">
			<h1><a href="{% url 'home' %}">Content Management System</a></h1>
			<nav>
				{% if user.is_authenticated %}
				<ul>
					<li>
						<form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
							{% csrf_token %}

							<button type="submit">Logout</button>
						</form>
					</li>
					<li><a href="{% url 'articles:create' %}" class="highlight"> Create New Article</a></li>
				
					{% else %}
						<li><a href="{% url 'accounts:login' %}" class="button">Login</a></li>
						<li><a href="{% url 'accounts:signup' %}" class="button">Sign Up</a></li>
					{% endif %}
				</ul>
			</nav>
		</header>
		{% block content %}
		{% endblock %}
	</div>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Home | Blog</title>
</head>
<body>
	<h1>HOME</h1>
	<p>Welcome to the homepage</p>
</body>
</html>